# Generated by Django 6.1.1 on 2026-09-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dutyschedule',
            constraint=models.UniqueConstraint(fields=('week_start_date', 'household'), name='unique_duty_schedule_per_week'),
        ),
    ]
