# Generated by Django 6.1.1 on 2026-09-07 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_dutyschedule_unique_duty_schedule_per_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swaprequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='swaprequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
